language: java
 notifications:
   email:
      recipients:
        - syed.muzakkir@egovernments.org
        - dinesh.s@egovernments.org
      on_success: [always|never|change] # default: change
      on_failure: [always|never|change] # default: always   
     

matrix:
   fast_finish: true
   include:
     - jdk: oraclejdk8
     
script: mvn clean verify
